### ISSUE TITLE
How can I avoid undefined when use in IOS?

### ISSUE THREAD

**Issue by minhkwan** [mybeon/react-native-schedule-exact-alarm-permission#1]
It works well in Android, tks!.
But when I build for IOS, it said that I have to manually link and cannot read property of undefined when access useSEA(). 
How can I fix this? Tks.

**Comment by beonma** [comment]
Hello @minhkwan , could you provide additional details, such as a screenshot of the error message, along with the specific part of the code where `useSEA()` is being called?

**Comment by minhkwan** [comment]
Error: The package 'react-native-schedule-exact-alarm-permission' doesn't seem to be linked. Make sure: 

- You have run 'pod install'
- You rebuilt the app after installing the package
- You are not using Expo Go
, js engine: hermes 



TypeError: Cannot read property 'useSEA' of undefined

This only appear when I hook, method from your library in IOS Device. I ran pod install. 
Tks!

**Comment by beonma** [comment]
The issue with the library isn't a bug, the error message you're seeing about linking in the console is a false positive and will be resolved in a future update to prevent it from appearing on iOS. 

As for `useSEA()` returning undefined, this is an expected behavior because the library doesn't include any iOS native code since it was developed exclusively for Android. Therefore, `useSEA()` will consistently return undefined on iOS.

To address this, consider implementing an if statement to handle undefined values or create separate code files for iOS and Android to manage platform-specific execution.

**Comment by minhkwan** [comment]
Tks! Due to it has been error from the import 'useSEA' i found a way to import conditionally whether it's IOS / Android.

**Comment by beonma** [comment]
The package has been updated. You can compare how your code would react compared to the previous version. Make sure to download the latest version.
